#pragma once

#include "sdkconfig.h"
#include "mesh_common.h"

#ifdef __cplusplus
extern "C" {
#endif

// Button GPIO configurations
#define DEVICE_CONTROLLER_BUTTON_UP_GPIO        CONFIG_DEVICE_CONTROLLER_BUTTON_UP_GPIO
#define DEVICE_CONTROLLER_BUTTON_DOWN_GPIO      CONFIG_DEVICE_CONTROLLER_BUTTON_DOWN_GPIO
#define DEVICE_CONTROLLER_BUTTON_LEFT_GPIO      CONFIG_DEVICE_CONTROLLER_BUTTON_LEFT_GPIO
#define DEVICE_CONTROLLER_BUTTON_RIGHT_GPIO     CONFIG_DEVICE_CONTROLLER_BUTTON_RIGHT_GPIO
#define DEVICE_CONTROLLER_BUTTON_CENTER_GPIO    CONFIG_DEVICE_CONTROLLER_BUTTON_CENTER_GPIO

// Button timing configurations
#define DEVICE_CONTROLLER_BUTTON_ACTIVE_LEVEL   CONFIG_DEVICE_CONTROLLER_BUTTON_ACTIVE_LEVEL
#define DEVICE_CONTROLLER_LONG_PRESS_TIME_MS    CONFIG_DEVICE_CONTROLLER_LONG_PRESS_TIME_MS
#define DEVICE_CONTROLLER_SHORT_PRESS_TIME_MS   CONFIG_DEVICE_CONTROLLER_SHORT_PRESS_TIME_MS
#define DEVICE_CONTROLLER_DOUBLE_CLICK_TIME_MS  CONFIG_DEVICE_CONTROLLER_DOUBLE_CLICK_TIME_MS
#define DEVICE_CONTROLLER_TIMEOUT_MS            CONFIG_DEVICE_CONTROLLER_TIMEOUT_MS

// Multi-device configurations
#ifdef CONFIG_DEVICE_CONTROLLER_ENABLE_MULTI_DEVICE
    #define DEVICE_CONTROLLER_ENABLE_MULTI_DEVICE   1
    #define DEVICE_CONTROLLER_MAX_DEVICES           CONFIG_DEVICE_CONTROLLER_MAX_DEVICES
#else
    #define DEVICE_CONTROLLER_ENABLE_MULTI_DEVICE   0
    #define DEVICE_CONTROLLER_MAX_DEVICES           1
#endif

// AC Parameter definitions from mesh_common.h
#define DEVICE_CONTROLLER_TEMP_MIN              AC_TEMP_MIN
#define DEVICE_CONTROLLER_TEMP_MAX              AC_TEMP_MAX

// AC Mode definitions
#define DEVICE_CONTROLLER_MODE_COOL             AC_MODE_COOL
#define DEVICE_CONTROLLER_MODE_HEAT             AC_MODE_HEAT  
#define DEVICE_CONTROLLER_MODE_FAN              AC_MODE_FAN
#define DEVICE_CONTROLLER_MODE_DRY              AC_MODE_DRY
#define DEVICE_CONTROLLER_MODE_AUTO             AC_MODE_AUTO

// AC Fan Speed definitions
#define DEVICE_CONTROLLER_FAN_SPEED_LOW         AC_FAN_SPEED_LOW
#define DEVICE_CONTROLLER_FAN_SPEED_MEDIUM      AC_FAN_SPEED_MEDIUM
#define DEVICE_CONTROLLER_FAN_SPEED_HIGH        AC_FAN_SPEED_HIGH

// AC Power State definitions
#define DEVICE_CONTROLLER_POWER_OFF             AC_POWER_OFF
#define DEVICE_CONTROLLER_POWER_ON              AC_POWER_ON

// Display configurations
#ifndef DEVICE_CONTROLLER_BOOT_DISPLAY_TIME_MS
#define DEVICE_CONTROLLER_BOOT_DISPLAY_TIME_MS       CONFIG_DEVICE_CONTROLLER_BOOT_DISPLAY_TIME_MS
#endif

#ifdef __cplusplus
}
#endif 