/*
 * SPDX-FileCopyrightText: 2021-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 */

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_ops.h"
#include "esp_err.h"
#include "esp_log.h"
#include "driver/i2c_master.h"
#include "esp_lvgl_port.h"
#include "lvgl.h"

#include "esp_lcd_panel_vendor.h" // For esp_lcd_panel_ssd1306_config_t if not transitively included

// Include for the UI generated by SquareLine Studio (or similar)
#include "gui_guider.h" // This should declare setup_ui AND extern lv_ui guider_ui

static const char *TAG = "DISPLAY"; // Changed tag for clarity

#define I2C_BUS_PORT  0

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////// Please update the following configuration according to your LCD spec //////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#define EXAMPLE_LCD_PIXEL_CLOCK_HZ    (400 * 1000)
#define EXAMPLE_PIN_NUM_SDA           3
#define EXAMPLE_PIN_NUM_SCL           4
#define EXAMPLE_PIN_NUM_RST           -1
#define EXAMPLE_I2C_HW_ADDR           0x3C

// The pixel number in horizontal and vertical
#define EXAMPLE_LCD_H_RES              128
#define EXAMPLE_LCD_V_RES              64

// Bit number used to represent command and parameter
#define EXAMPLE_LCD_CMD_BITS           8
#define EXAMPLE_LCD_PARAM_BITS         8


// The global guider_ui struct is now expected to be defined in gui_guider.c
// and declared as extern in gui_guider.h. So, remove the definition from here.
lv_ui guider_ui; 

void display_init(void)
{
    ESP_LOGI(TAG, "Initialize I2C bus");
    i2c_master_bus_handle_t i2c_bus = NULL;
    i2c_master_bus_config_t bus_config = {
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .glitch_ignore_cnt = 7,
        .i2c_port = I2C_BUS_PORT,
        .sda_io_num = EXAMPLE_PIN_NUM_SDA,
        .scl_io_num = EXAMPLE_PIN_NUM_SCL,
        .flags.enable_internal_pullup = true,
    };
    ESP_ERROR_CHECK(i2c_new_master_bus(&bus_config, &i2c_bus));

    ESP_LOGI(TAG, "Install panel IO");
    esp_lcd_panel_io_handle_t io_handle = NULL;
    esp_lcd_panel_io_i2c_config_t io_config = {
        .dev_addr = EXAMPLE_I2C_HW_ADDR,
        .scl_speed_hz = EXAMPLE_LCD_PIXEL_CLOCK_HZ,
        .control_phase_bytes = 1,               // According to SSD1306 datasheet
        .lcd_cmd_bits = EXAMPLE_LCD_CMD_BITS,   // According to SSD1306 datasheet
        .lcd_param_bits = EXAMPLE_LCD_CMD_BITS, // According to SSD1306 datasheet
        .dc_bit_offset = 6,                     // According to SSD1306 datasheet
    };
    ESP_ERROR_CHECK(esp_lcd_new_panel_io_i2c(i2c_bus, &io_config, &io_handle));

    ESP_LOGI(TAG, "Install SSD1306 panel driver");
    esp_lcd_panel_handle_t panel_handle = NULL;
    esp_lcd_panel_dev_config_t panel_config = {
        .bits_per_pixel = 1,
        .reset_gpio_num = EXAMPLE_PIN_NUM_RST,
    };
    // Specific config for SSD1306
    esp_lcd_panel_ssd1306_config_t ssd1306_config = {
        .height = EXAMPLE_LCD_V_RES,
    };
    panel_config.vendor_config = &ssd1306_config;
    ESP_ERROR_CHECK(esp_lcd_new_panel_ssd1306(io_handle, &panel_config, &panel_handle));

    ESP_ERROR_CHECK(esp_lcd_panel_reset(panel_handle));
    ESP_ERROR_CHECK(esp_lcd_panel_init(panel_handle));
    ESP_ERROR_CHECK(esp_lcd_panel_disp_on_off(panel_handle, true));

    ESP_LOGI(TAG, "Initialize LVGL");
    const lvgl_port_cfg_t lvgl_cfg = ESP_LVGL_PORT_INIT_CONFIG();
    // Note: lvgl_port_init may try to initialize esp_timer.
    // Check for "esp_timer: Task is already initialized" if it occurs.
    esp_err_t lvgl_init_res = lvgl_port_init(&lvgl_cfg);
    if (lvgl_init_res != ESP_OK && lvgl_init_res != ESP_ERR_INVALID_STATE) {
        // ESP_ERR_INVALID_STATE might mean esp_timer already initialized, which is fine.
        ESP_LOGE(TAG, "lvgl_port_init failed: %s", esp_err_to_name(lvgl_init_res));
        ESP_ERROR_CHECK(lvgl_init_res); // Abort on other errors
    } else if (lvgl_init_res == ESP_ERR_INVALID_STATE) {
        ESP_LOGW(TAG, "lvgl_port_init returned ESP_ERR_INVALID_STATE (esp_timer likely already initialized, which is okay).");
    }


    const lvgl_port_display_cfg_t disp_cfg = {
        .io_handle = io_handle,
        .panel_handle = panel_handle,
        // For monochrome displays with esp_lvgl_port, full buffer is often required.
        // The size is in terms of pixels that LVGL can render into.
        .buffer_size = EXAMPLE_LCD_H_RES * EXAMPLE_LCD_V_RES, 
        .double_buffer = true, // Keep true for now, can be set to false if issues or for memory saving
        .hres = EXAMPLE_LCD_H_RES,
        .vres = EXAMPLE_LCD_V_RES,
        .monochrome = true, 
        .rotation = {
            .swap_xy = false,
            .mirror_x = false,
            .mirror_y = false,
        }
    };
    lv_disp_t *disp = lvgl_port_add_disp(&disp_cfg);
    if (disp == NULL) {
        ESP_LOGE(TAG, "lvgl_port_add_disp failed!");
        // Handle error, perhaps by not proceeding with UI setup
        return;
    }

    /* Rotation of the screen - typically not needed for fixed orientation OLEDs */
    // lv_disp_set_rotation(disp, LV_DISP_ROT_NONE);

    ESP_LOGI(TAG, "Setting up UI using gui_guider functions...");
    
    // Lock the LVGL mutex before calling UI functions
    if (lvgl_port_lock(0)) {
        // setup_ui now uses the guider_ui declared as extern (and defined in gui_guider.c)
        setup_ui(&guider_ui); 
        lvgl_port_unlock();
        ESP_LOGI(TAG, "UI setup complete.");
    } else {
        ESP_LOGE(TAG, "Failed to acquire LVGL mutex for UI setup.");
    }
}
